linters-settings:
  golint:
    min-confidence: 0
linters:
  disable-all: true
  enable:
    - typecheck
    - goimports
    - misspell
    - govet
    - ineffassign
    - gosimple
    - deadcode
    #    - structcheck
    - unused
    - errcheck
service:
  golangci-lint-version: 1.45.2
