// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"
)

type Querier interface {
	AddFavorite(ctx context.Context, id int64) error
	CreateComment(ctx context.Context, arg CreateCommentParams) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (int64, error)
	CreateUserFollower(ctx context.Context, arg CreateUserFollowerParams) error
	CreateUserVideo(ctx context.Context, arg CreateUserVideoParams) (int64, error)
	CreateVideo(ctx context.Context, arg CreateVideoParams) (int64, error)
	DeleteComment(ctx context.Context, id int64) error
	DeleteFavorite(ctx context.Context, id int64) error
	DeleteFavoriteByUserId(ctx context.Context, userID int64) error
	DeleteUserFollower(ctx context.Context, arg DeleteUserFollowerParams) error
	DeleteUserVideo(ctx context.Context, arg DeleteUserVideoParams) error
	DeleteVideo(ctx context.Context, id int64) error
	GetComment(ctx context.Context, id int64) (GetCommentRow, error)
	GetCommentsByVideoId(ctx context.Context, videoID int64) ([]GetCommentsByVideoIdRow, error)
	GetUserByUserID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, name string) (User, error)
	GetUserFollower(ctx context.Context, arg GetUserFollowerParams) (UserFollower, error)
	GetUserFollowersByFromUserID(ctx context.Context, fromID int64) ([]UserFollower, error)
	GetUserFollowersByToUserID(ctx context.Context, toID int64) ([]UserFollower, error)
	GetUserVideo(ctx context.Context, arg GetUserVideoParams) (UserVideo, error)
	GetVideoByID(ctx context.Context, id int64) (GetVideoByIDRow, error)
	GetVideoByUserId(ctx context.Context, userID int64) ([]UserVideo, error)
	GetVideosByDate(ctx context.Context, arg GetVideosByDateParams) ([]GetVideosByDateRow, error)
	GetVideosByUserID(ctx context.Context, arg GetVideosByUserIDParams) ([]GetVideosByUserIDRow, error)
	GetVideosByUserVideo(ctx context.Context, userID int64) ([]GetVideosByUserVideoRow, error)
	GetVideosFavorite(ctx context.Context, id int64) ([]GetVideosFavoriteRow, error)
	IsExistRelations(ctx context.Context, arg IsExistRelationsParams) (int64, error)
	UpdateUserFollowCount(ctx context.Context, arg UpdateUserFollowCountParams) error
	UpdateUserFollowerCount(ctx context.Context, arg UpdateUserFollowerCountParams) error
	UpdateVideoCommentCount(ctx context.Context, arg UpdateVideoCommentCountParams) error
	UpdateVideoFavoriteCount(ctx context.Context, arg UpdateVideoFavoriteCountParams) error
	UserFollowCount(ctx context.Context) (int64, error)
	UserFollowerCount(ctx context.Context) (int64, error)
}

var _ Querier = (*Queries)(nil)
