name: Run unit tests

on: # 触发此工作流的事件
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 7963:6379
    steps:
      # 创建数据库
      - name: Create mysql database auth
        uses: icomponent/mysql-action@master
        with:
          VERSION: 8.0
          CONTAINER_NAME: mysql_80
          PORT_MAPPING: 3366:3306
          ROOT_PASSWORD: 123456
          DATABASE: douyin

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: check out code into the go module directory
        uses: actions/checkout@v2

      - name: install golang-cli
        run: make install_golang-cli

      # 数据库迁移
      - name: make migration
        run: make migrate_up
      # 测试
      - name: Test
        run: make test
